services:
  promocodefactory:
    image: ghcr.io/giuliomat/bdt-project:latest
    ports:
      - "8080:8080"
    container_name: container_promocodefactry
    depends_on:
      - db
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - db_data:/var/lib/postgresql/data 
    container_name: container_db_postgresql
volumes:
  db_data: