services:
  promocodefactory:
    container_name: container_promocodefactory
    image: ghcr.io/yauhenilyushenka/promocodefactory:latest
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    container_name: container_db_postgresql
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: promocodefactorydb
    volumes:
      - db_data:/var/lib/postgresql/data 
volumes:
  db_data: