name: "Setup .NET and Restore dependencies"

runs:
  using: "composite"

  steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies for the project
      run: dotnet restore Base/src/PromoCodeFactory.sln
      shell: bash
