# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: PromoCodeFactory

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    env:
      ROOT_PROJECT_PATH: Base/src

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup .NET and Restore Dependecnies
      uses: ./.github/actions/Setup-NET-and-Restore-Dependecies
      
    - name: Build project
      run: dotnet build ${{ env.ROOT_PROJECT_PATH }}/PromoCodeFactory.sln

  test:
    name: Testing
    needs: build
    runs-on: ubuntu-latest
    
    env:
      ROOT_TEST_PROJECT_PATH: Base/src/PromoCodeFactory.UnitTests
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup .NET and Restore Dependecnies
      uses: ./.github/actions/Setup-NET-and-Restore-Dependecies

    - name: Test
      run: dotnet test ${{ env.ROOT_TEST_PROJECT_PATH }}/PromoCodeFactory.UnitTests.csproj
      
  docker:
    name: Build and Push Docker Image
    needs: test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # github registry with repo secrets
    - name: Log in to GitHub Container Registry
      run: echo ${{ secrets.GH_PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build and push Docker image
      run: |
        REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
        docker build ./Base/src/PromoCodeFactory.WebHost/Dockerfile -t ghcr.io/${REPO_NAME}/promocodefactory:latest
        docker push ghcr.io/${REPO_NAME}/promocodefactory:latest

